events {
    worker_connections 1024;
}

http {
    include mime.types;

    upstream central_app {
        server central_server:8001;
    }

    # --- Redirect HTTP to HTTPS ---
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    # --- HTTPS Server ---
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location /static/ {
            alias /app/static/;
        }

        location / {
            proxy_pass http://central_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}